version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    versioning-strategy: "increase"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
