blank_issues_enabled: false
contact_links:
  - name: Support the project
    url: https://github.com/sponsors/panva
    about:
      To make sure you get your questions answered
  - name: ❓ Question
    url: https://github.com/panva/node-oidc-provider/discussions/894
    about:
      Have a question about using oidc-provider? Support the project and then head over to the discussions "Q&A" Category
  - name: 💡 Feature proposal
    url: https://github.com/panva/node-oidc-provider/discussions/893
    about:
      Have a proposal for a new feature? Head over to the discussions "Ideas" Category
  - name: Report a security vulnerability
    url: https://en.wikipedia.org/wiki/Responsible_disclosure
    about:
      Do not disclose vulnerabilities via issues or discussions. Reach out to the project team
      via e.g. email, we'll work together on patching the vulnerability and follow some form of
      Responsible disclosure once fixed. Thank you.
