declare const _: any;
declare const format: any, URL: any;
declare const crypto: any;
declare const createKeyStore: any;
declare const LRU: any;
declare const assert: any;
declare const base64url: any;
declare const httpRequest: any;
declare const uuid: any;
declare const epochTime: any;
declare const instance: any;
declare const InvalidClientMetadata: any;
declare const getSchema: any;
declare const NOOP: () => void;
declare const KEY_ATTRIBUTES: string[];
declare const KEY_TYPES: string[];
declare const LOOPBACKS: string[];
declare const nonSecretAuthMethods: string[];
declare const clientEncryptions: string[];
declare const signAlgAttributes: string[];
declare function isDefinedAndMatches(prop: any): false | RegExpMatchArray | null;
declare function isDefinedAndStartsWithHS(prop: any): boolean;
declare function handled(kty: any): boolean;
declare function stripFragment(uri: any): any;
declare const JWKStore: any;
