name: Release

permissions: {}

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+']

jobs:
  npm:
    if: ${{ github.repository == 'panva/node-oidc-provider' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org
      - run: npm install -g npm@latest
      - run: npm stage publish

  cleanup:
    needs:
      - npm
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - run: git push origin $GITHUB_SHA:v9.x
      - run: git push origin HEAD:main

  github:
    needs:
      - npm
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 2
      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: lts/*
          cache: 'npm'
      - run: node .release-notes.cjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
